---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
knitr::opts_chunk$set(warning=FALSE)
library(ggplot2)
library(RColorBrewer)

activity <- read.csv("./activity.csv")
activity$date <- as.POSIXct(activity$date, "%Y-%m-%d")
weekday <-  weekdays(activity$date)
activity <- cbind(activity, weekday)


## What is mean total number of steps taken per day?
activity_total_steps <- with(activity, aggregate(steps, by = list(date), FUN=sum, na.rm = TRUE))
names(activity_total_steps) <- c("date", "steps")
png("plot1.png", width = 480, height = 480)
hist(activity_total_steps$steps, main = "Total Daily Steps per Day",
     xlab = "Total number of steps taken per day",
     col = brewer.pal(n=8, name = "Spectral"),
     ylim = c(0,20), 
     breaks = seq(0, 25000, by = 2500))
dev.off()
mean(activity_total_steps$steps)
### The mean total number of steps taken per day is 9354 steps


## What is the average daily activity pattern?
average_daily_activity <- aggregate(activity$steps, by = list(activity$interval), FUN=mean, na.rm = TRUE)
names(average_daily_activity) <- c("interval","mean")
png("plot2.png", width = 480, height = 480)
plot(average_daily_activity$interval, average_daily_activity$mean, type = "l", lwd = 1,
     xlab = "Interval", ylab = "Average number of steps", main = "Average Number of Steps per Intervals")
dev.off()
average_daily_activity[which.max(average_daily_activity$mean), ]$interval
### On average across all the days in the dataset, the 5-minute interval 835 contains the maximum number of steps


## Imputing missing values
sum(is.na(activity$steps))
### The total number of missing values in the dataset is 2304
imputed_steps <- average_daily_activity$mean[match(activity$interval, average_daily_activity$interval)]
activity_imputed <-  transform(activity, steps = ifelse(is.na(activity$steps),
                                                        yes = imputed_steps,
                                                        no = activity$steps))
total_steps_imputed <- aggregate(steps ~ date, activity_imputed, sum)
names(total_steps_imputed) <- c("date","daily_steps")
png("plot3.png", width = 480, height = 480)
hist(total_steps_imputed$daily_steps, xlab = "Total number of steps per day", ylim = c(0,30),
     col = brewer.pal(n=8, name = "RdBu"),
     main = "Steps taken daily",
     breaks = seq(0,25000, by=2500))
dev.off()


## Are there differences in activity patterns between weekdays and weekends?
activity$date <- as.Date(strptime(activity$date, format = "%Y-%m-%d"))
activity$datetype <- sapply(activity$date, function(x) {
  if (weekdays(x) == "Saturday" | weekdays(x) == "Sunday")
  {y <- "Weekend"} else
  {y <- "Weekday"}
  y
})
activity_by_date <- aggregate(steps~interval + datetype, activity, mean, na.rm = TRUE)
png("plot4.png", width = 480, height = 480)
ggplot(activity_by_date, aes(x = interval, y = steps, color = datetype)) + geom_line() +
  labs(title = "Average Daily Steps by Type of Date", x = "Interval", y = "Average number of steps") +
  facet_wrap(~datetype, ncol = 1, nrow = 2)
dev.off()
